modLoader = "javafml"
loaderVersion = "[38,)"

license = "Apache-2.0"
issueTrackerURL="https://github.com/badasintended/badpackets/issues"
showAsResourcePack=false

[[mods]]
modId = "badpackets_testmod"
version = "1"
displayName = "Bad Packets Testmod"
description = "Bad Packets Testmod"
