modLoader = "javafml"
loaderVersion = "[1,)"

license = "Apache-2.0"
issueTrackerURL = "https://github.com/badasintended/badpackets/issues"

[[mods]]
modId = "badpackets"
version = "${version}"
displayName = "Bad Packets"
description = "Allow packet messaging between multiple modding platform."
authors = "deirn"
logoFile = "badpackets.png"

[[mixins]]
config = "badpackets.mixins.json"

[[dependencies.badpackets]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"
