modLoader = "javafml"
loaderVersion = "[38,)"

license = "Apache-2.0"
issueTrackerURL = "https://github.com/badasintended/badpackets/issues"
showAsResourcePack = false

[[mods]]
modId = "badpackets"
version = "${version}"
displayName = "Bad Packets"
description = "Allow packet messaging between multiple modding platform."
authors = "deirn"
logoFile = "badpackets.png"

[[dependencies.badpackets]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"
