name: head
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=git_hash::${GITHUB_SHA:0:7}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/*.gradle.kts') }}
      - run: ./gradlew build
        env:
          GIT_HASH: ${{ steps.vars.outputs.git_hash }}
      - uses: actions/upload-artifact@v2
        with:
          name: wthit-fabric-${{ steps.vars.outputs.git_hash }}
          path: "./platform/fabric/build/libs/**.jar"
      - uses: actions/upload-artifact@v2
        with:
          name: wthit-forge-${{ steps.vars.outputs.git_hash }}
          path: "./platform/forge/build/libs/**.jar"
