name: release
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: chmod +x gradlew
      - run: ./gradlew build publish curseforge modrinth
        env:
          MOD_VERSION: ${{ steps.vars.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}
          CURSEFORGE_API: ${{ secrets.CURSEFORGE_API }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - uses: sylwit/install-b2-cli-action@ae80099fa373ec5aef6fa509aa3012fcdd936b6d
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
      - run: |
          b2 sync --replaceNewer .b2 b2://maven-bai-lol
          b2 clear-account
      - uses: actions/upload-artifact@v3
        with:
          name: wthit-fabric-${{ steps.vars.outputs.version }}
          path: "./platform/fabric/build/libs/**.jar"
      - uses: actions/upload-artifact@v3
        with:
          name: wthit-forge-${{ steps.vars.outputs.version }}
          path: "./platform/forge/build/libs/**.jar"
      - uses: alexellis/upload-assets@259de5111cb56966d046ced998941e93f91d2c93
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: |
            [
              "./platform/*/build/libs/*[0-9.].jar",
              "./platform/*/build/libs/*[0-9.]-api.jar"
            ]
