name: head
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "git_hash=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - run: chmod +x gradlew
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/*.gradle.kts') }}
      - run: ./gradlew build
        env:
          GIT_HASH: ${{ steps.vars.outputs.git_hash }}
      - uses: actions/upload-artifact@v4
        with:
          name: badpackets-${{ steps.vars.outputs.git_hash }}
          path: "./platform/*/build/libs/**.jar"
