name: release
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: chmod +x gradlew
      - run: ./gradlew build publish curseforge modrinth
        env:
          MOD_VERSION: ${{ steps.vars.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}
          CURSEFORGE_API: ${{ secrets.CURSEFORGE_API }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: badpackets-${{ steps.vars.outputs.git_hash }}
          path: "./platform/*/build/libs/**.jar"
      - uses: alexellis/upload-assets@259de5111cb56966d046ced998941e93f91d2c93
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: |
            [
              "./platform/*/build/libs/*[0-9.].jar",
              "./platform/*/build/libs/*[0-9.]-api.jar"
            ]
