name: release
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - run: chmod +x gradlew
      - run: ./gradlew build publishMods publish
        env:
          MOD_VERSION: ${{ steps.vars.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}
          CURSEFORGE_API: ${{ secrets.CURSEFORGE_API }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: badpackets-${{ steps.vars.outputs.git_hash }}
          path: "./platform/*/build/libs/**.jar"
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          files: |
            ./platform/*/build/libs/*[0-9.].jar
            ./platform/*/build/libs/*[0-9.]-api.jar
